apiVersion: v1
kind: Service
metadata:
  name: pourover-timer-service
  namespace: pourover-timer
  labels:
    app: pourover-timer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # For AWS
    cloud.google.com/neg: '{"ingress": true}'  # For GCP
spec:
  type: LoadBalancer
  selector:
    app: pourover-timer
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  sessionAffinity: None
